name: PipelineWorkflow


on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main

jobs:
    build:
       name: Azure Pipeline
       runs-ob: ubuntu-latest
       steps:
        - name : Azure Pipeline Action
          uses : Azure/pipelines@v1
          with :
            azure-devops-project-url: https://dev.azure.com/anandshuklanew919/LearningProject
            azure-pipeline-name: 'DevOpsAnandShukla.AzureDevOpsLearning'
            azure-devops-token: ${{secret.AZURE_DEVOPS_TOKEN}}